Repository IT2901-SINTEF01/frontend, pull requests merged in 2021-02, with the labels that each got.

#7 Setup React Template
  .eslintignore
  .eslintrc.js
  .github/workflows/node.js.yml
  .gitignore
  .prettierignore
  .prettierrc.js
  README.md
  craco.config.js
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/components/Filler.tsx
  src/index.css
  src/index.tsx
  src/react-app-env.d.ts
  src/setupTests.ts
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: enhancement

#8 2 setup ci
  .github/workflows/node.js.yml
Labels: enhancement

#13 Create .restyled.yaml
  .restyled.yaml
Labels: linting

#16 Fix bug with lock hashing
  .github/workflows/ci.yml
Labels: enhancement

#22 Update README with relevant information
  README.md
  SINTEF_logo.png
Labels: documentation

#33 Update component folder structure
  src/components/atoms/Filler.tsx
  src/components/molecules/.keep
  src/components/organisms/.keep
  src/index.tsx
Labels: enhancement

#35 Add proxy in package.json
  package.json
Labels: enhancement

#39 Remove CI lint job
  .github/workflows/ci.yml
Labels: CI/CD

#41 No spell checking in non-source files
  sider.yml
Labels: bug

#42 Change tailwind with styled components
  craco.config.js
  package.json
  tailwind.config.js
  yarn.lock
Labels: enhancement

#43 Revert "Change tailwind with styled components"
  craco.config.js
  package.json
  tailwind.config.js
  yarn.lock
Labels: enhancement
